#!/bin/bash

##########################################################################################

show_man_page() {
    echo "===== Chocholousek Picons - online installation script ====="
    echo "USAGE:"
    echo '      wget -qO- --no-check-certificate "https://github.com/s3n0/e2plugins/raw/master/ChocholousekPicons/online-setup" | bash -s <ARGUMENT>'
    echo "ARGUMENT:"
    echo "      install ....... install the plugin (with the Enigma2 fast restart)"
    echo "      uninstall ..... uninstall the plugin (with the Enigma2 fast restart)"
    echo "      del-config .... delete the plugin configuration only & exit the script"
    echo "      del-plugin .... delete the plugin directory only & exit the script"
}

e2_stop() {
    echo "Enigma2 stops"
    [ -d /etc/dpkg ] && systemctl stop enigma2 || init 4
    sleep 5
}

e2_start() {
    echo "Enigma2 starts"
    [ -d /etc/dpkg ] && systemctl start enigma2 || init 3
}

plugin_cfg_del() {
    sed -i '/config\.plugins\.chocholousekpicons/d' /etc/enigma2/settings
    echo "The plugin configuration was removed from the 'settings' file - '/etc/enigma2/settings'"
}

plugin_dir_del() {
    rm -rf /usr/lib/enigma2/python/Plugins/Extensions/ChocholousekPicons/
    echo "The plugin directory was removed from the Enigma2 - '/usr/lib/enigma2/python/Plugins/Extensions/ChocholousekPicons/'"
}

#plugin_cfg_del_old_versions() {
#    V_FILE="/usr/lib/enigma2/python/Plugins/Extensions/ChocholousekPicons/version.txt"
#    if [ -f $V_FILE ]; then
#        V_CH1="$(head -c 1 $V_FILE)"
#        if awk 'BEGIN {return_code=('$V_CH1' <= '4') ? 0 : 1; exit} END {exit return_code}'; then plugin_cfg_del; fi
#    fi
}

##########################################################################################

[ -z "$1" ] && { show_man_page; echo -e "\nError ! No argument found !"; exit 1; }

PKGNAME="enigma2-plugin-extensions-chocholousek-picons"

case "$1" in
    install)
        # retrieve the latest version number (from internet)
    ### VER="$(wget -qO- --proxy off --no-check-certificate https://github.com/s3n0/e2plugins/raw/master/ChocholousekPicons/src/version.txt)"
    ### VER="$(wget -qO- --proxy off --no-check-certificate https://raw.githubusercontent.com/s3n0/e2plugins/master/ChocholousekPicons/src/version.txt)"
        VER="$(wget -qO- --proxy off --no-check-certificate https://github.com/s3n0/e2plugins/blob/master/ChocholousekPicons/src/version.txt?raw=true)"
        [ -z "$VER" ] && { echo "Error ! The online version was not recognized !"; exit 1; }
        # download the plugin installation package from internet
        FNAME="${PKGNAME}_${VER}_all.$([ -d /etc/dpkg ] && echo -n 'deb' || echo -n 'ipk')"
    ### wget -qO "/tmp/${FNAME}" --proxy off --no-check-certificate "https://github.com/s3n0/e2plugins/raw/master/ChocholousekPicons/released_build/${FNAME}" || { echo "Error ! File download failed !"; exit 1; }
    ### wget -qO "/tmp/${FNAME}" --proxy off --no-check-certificate "https://raw.githubusercontent.com/s3n0/e2plugins/master/ChocholousekPicons/released_build/${FNAME}" || { echo "Error ! File download failed !"; exit 1; }
        wget -qO "/tmp/${FNAME}" --proxy off --no-check-certificate "https://github.com/s3n0/e2plugins/blob/master/ChocholousekPicons/released_build/${FNAME}?raw=true" || { echo "Error ! File download failed !"; exit 1; }
        # re-install
        if [ -d /etc/dpkg ]; then
            dpkg -r $PKGNAME                # dpkg -r "${FNAME%%_*}"
            dpkg -i /tmp/$FNAME
        else
            opkg remove $PKGNAME            # opkg remove "${FNAME%%_*}"
            opkg install /tmp/$FNAME
        fi
        rm -f "/tmp/${FNAME}"
        e2_stop
        plugin_cfg_del
        e2_start
        ;;
    uninstall)
        if [ -d /etc/dpkg ]; then
            dpkg -r $PKGNAME
        else
            opkg remove $PKGNAME
        fi
        e2_stop
        plugin_cfg_del
        plugin_dir_del
        e2_start
        ;;
    del-config)
        e2_stop
        plugin_cfg_del
        e2_start
        ;;
    del-plugin)
        e2_stop
        plugin_dir_del
        e2_start
        ;;
    *)
        show_man_page
        echo -e "\nError ! Wrong argument !"
        exit 1
        ;;
esac

exit 0
