#!/bin/bash

[ -z "$1" ] && { echo "Error ! No 'install|uninstall' argument found !"; exit 1; }

PKGNAME="enigma2-plugin-extensions-chocholousek-picons"

case "$1" in
    install)
        # retrieve the online version number and download file
        VER="$(wget -qO- --proxy off --no-check-certificate https://github.com/s3n0/e2plugins/raw/master/ChocholousekPicons/src/version.txt)"
        [ -z "$VER" ] && { echo "Error ! The online version was not recognized !"; exit 1; }
        # download the latest version from internet
        FNAME="${PKGNAME}_${VER}_all.$([ -d /etc/dpkg ] && echo -n 'deb' || echo -n 'ipk')"
        wget -qO "/tmp/${FNAME}" --no-check-certificate "https://github.com/s3n0/e2plugins/raw/master/ChocholousekPicons/released_build/${FNAME}" || { echo "Error ! File download failed !"; exit 1; }
        # re-install
        if [ -d /etc/dpkg ]; then
            dpkg -r $PKGNAME                # dpkg -r ${FNAME%%_*}
            dpkg -i /tmp/$FNAME
        else
            opkg remove $PKGNAME            # opkg remove ${FNAME%%_*}
            opkg install /tmp/$FNAME
        fi
        rm -f "/tmp/${FNAME}"
        ;;
    uninstall)
        if [ -d /etc/dpkg ]; then
            dpkg -r $PKGNAME
        else
            opkg remove $PKGNAME
        fi
        rm -rf /usr/lib/enigma2/python/Plugins/Extensions/ChocholousekPicons/
        ;;
    *)
        echo "Error ! Argument 'install|uninstall' was not found !"
        exit 1
        ;;
esac

# enigma2 fast restart + delete all ChocholousekPicons settings (plugin configuration)
if [ -d /etc/dpkg ]; then
    systemctl stop enigma2; sleep 5; sed -i '/config\.plugins\.chocholousekpicons/d' /etc/enigma2/settings; systemctl start enigma2
else
    init 4; sleep 5; sed -i '/config\.plugins\.chocholousekpicons/d' /etc/enigma2/settings; init 3
fi

exit 0
